### PR TITLE
Migrate Symfony3

### PR DESCRIPTION
**Pull request by benji07**
Missing deps:

- [ ] "nelmio/alice": "2.1.*",
- [ ] "knplabs/friendly-contexts": "0.5.*",
- [ ] "behat/symfony2-extension": "2.0.*",

### CODE REVIEW

**Comment by benji07** [comment]
Should we remove all extra extension of behat ?

**Comment by maximecolin** [comment]
I think we could. Some project doesn't need behat and/or extra extension. We must not force behat dependencies in the standard distribution.

**Comment by woecifaun** [comment]
I would follow @maximecolin advice.

**Comment by nervo** [comment]
:+1:

**Comment by Tom32i** [comment]
:+1:

**Pull request merged**
